-- Internal Task Management foundation
-- The live Singapore project already has this migration applied.
create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role text not null default 'employee' check (role in ('supervisor','employee')), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.employees (id uuid primary key default gen_random_uuid(), full_name text not null unique, profile_id uuid unique references public.profiles(id) on delete set null, active boolean not null default true, display_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.weekly_periods (id uuid primary key default gen_random_uuid(), week_start date not null unique, week_end date not null, label text not null, status text not null default 'active' check(status in ('planned','active','closed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(week_end>=week_start));
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), period_id uuid not null references public.weekly_periods(id), title text not null, description text, priority text not null default 'medium' check(priority in ('low','medium','high','critical')), weight numeric(8,2) not null default 1 check(weight>0), due_at timestamptz, assigned_by uuid references public.profiles(id), assigned_to uuid not null references public.employees(id), status text not null default 'assigned' check(status in ('assigned','in_progress','submitted','approved','revision','rejected','closed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.task_claims (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade, employee_id uuid not null references public.employees(id), realization_summary text not null, completion_percent int not null default 100 check(completion_percent between 0 and 100), submitted_at timestamptz not null default now(), version int not null default 1 check(version>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(task_id,version));
create table if not exists public.evidence_files (id uuid primary key default gen_random_uuid(), claim_id uuid not null references public.task_claims(id) on delete cascade, storage_path text not null unique, file_name text not null, mime_type text, file_size bigint, uploaded_at timestamptz not null default now());
create table if not exists public.task_evaluations (id uuid primary key default gen_random_uuid(), claim_id uuid not null unique references public.task_claims(id) on delete cascade, evaluator_id uuid references public.profiles(id), score numeric(5,2) check(score between 0 and 100), decision text not null check(decision in ('approved','revision','rejected')), feedback text, evaluated_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.leaderboard_weekly (period_id uuid not null references public.weekly_periods(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, total_assigned int not null default 0,total_submitted int not null default 0,total_approved int not null default 0,overdue_count int not null default 0,completion_rate numeric(6,2) not null default 0,on_time_rate numeric(6,2) not null default 0,avg_score numeric(6,2) not null default 0,weighted_points numeric(12,2) not null default 0,rank int,refreshed_at timestamptz not null default now(),primary key(period_id,employee_id));
create table if not exists public.activity_log (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create or replace function public.is_supervisor() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role='supervisor') $$;
create or replace function public.my_employee_id() returns uuid language sql stable security definer set search_path=public as $$ select e.id from public.employees e where e.profile_id=auth.uid() and e.active limit 1 $$;

alter table public.profiles enable row level security;alter table public.employees enable row level security;alter table public.weekly_periods enable row level security;alter table public.tasks enable row level security;alter table public.task_claims enable row level security;alter table public.evidence_files enable row level security;alter table public.task_evaluations enable row level security;alter table public.leaderboard_weekly enable row level security;alter table public.activity_log enable row level security;

create policy "profiles self or supervisor read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_supervisor());
create policy "employees authenticated read" on public.employees for select to authenticated using(true);
create policy "periods authenticated read" on public.weekly_periods for select to authenticated using(true);
create policy "tasks scoped read" on public.tasks for select to authenticated using(public.is_supervisor() or assigned_to=public.my_employee_id());
create policy "tasks supervisor write" on public.tasks for all to authenticated using(public.is_supervisor()) with check(public.is_supervisor());
create policy "claims scoped read" on public.task_claims for select to authenticated using(public.is_supervisor() or employee_id=public.my_employee_id());
create policy "claims employee insert" on public.task_claims for insert to authenticated with check(employee_id=public.my_employee_id() and exists(select 1 from public.tasks t where t.id=task_id and t.assigned_to=public.my_employee_id()));
create policy "evidence scoped read" on public.evidence_files for select to authenticated using(public.is_supervisor() or exists(select 1 from public.task_claims c where c.id=claim_id and c.employee_id=public.my_employee_id()));
create policy "evidence employee insert" on public.evidence_files for insert to authenticated with check(exists(select 1 from public.task_claims c where c.id=claim_id and c.employee_id=public.my_employee_id()));
create policy "evaluation scoped read" on public.task_evaluations for select to authenticated using(public.is_supervisor() or exists(select 1 from public.task_claims c where c.id=claim_id and c.employee_id=public.my_employee_id()));
create policy "evaluation supervisor write" on public.task_evaluations for all to authenticated using(public.is_supervisor()) with check(public.is_supervisor());
create policy "leaderboard authenticated read" on public.leaderboard_weekly for select to authenticated using(true);
create policy "activity supervisor read" on public.activity_log for select to authenticated using(public.is_supervisor());

insert into public.employees(full_name,display_order) values ('Endang Mirah Ayu',1),('Citra Aries',2),('Heri Syamsudin',3) on conflict(full_name) do update set display_order=excluded.display_order;

insert into storage.buckets(id,name,public,file_size_limit) values('task-evidence','task-evidence',false,10485760) on conflict(id) do update set public=false,file_size_limit=10485760;
create policy "evidence storage employee read" on storage.objects for select to authenticated using(bucket_id='task-evidence' and (public.is_supervisor() or (storage.foldername(name))[1]=public.my_employee_id()::text));
create policy "evidence storage employee insert" on storage.objects for insert to authenticated with check(bucket_id='task-evidence' and (storage.foldername(name))[1]=public.my_employee_id()::text);

create or replace function public.sync_task_status_from_claim() returns trigger language plpgsql security definer set search_path=public as $$ begin update public.tasks set status='submitted',updated_at=now() where id=new.task_id; return new; end $$;
drop trigger if exists trg_claim_submit on public.task_claims;create trigger trg_claim_submit after insert on public.task_claims for each row execute function public.sync_task_status_from_claim();
create or replace function public.sync_task_status_from_evaluation() returns trigger language plpgsql security definer set search_path=public as $$ declare tid uuid; begin select task_id into tid from public.task_claims where id=new.claim_id; update public.tasks set status=new.decision,updated_at=now() where id=tid; return new; end $$;
drop trigger if exists trg_eval_status on public.task_evaluations;create trigger trg_eval_status after insert or update on public.task_evaluations for each row execute function public.sync_task_status_from_evaluation();

create or replace function public.refresh_weekly_leaderboard(p_period uuid) returns void language plpgsql security definer set search_path=public as $$ begin
insert into public.leaderboard_weekly(period_id,employee_id,total_assigned,total_submitted,total_approved,overdue_count,completion_rate,on_time_rate,avg_score,weighted_points,refreshed_at)
select p_period,e.id,count(t.id),count(c.id),count(ev.id) filter(where ev.decision='approved'),count(t.id) filter(where t.due_at<now() and t.status not in('approved','closed')),
case when count(t.id)=0 then 0 else 100.0*count(ev.id) filter(where ev.decision='approved')/count(t.id) end,
case when count(ev.id) filter(where ev.decision='approved')=0 then 0 else 100.0*count(ev.id) filter(where ev.decision='approved' and c.submitted_at<=coalesce(t.due_at,c.submitted_at))/count(ev.id) filter(where ev.decision='approved') end,
coalesce(avg(ev.score) filter(where ev.decision='approved'),0),coalesce(sum(t.weight*coalesce(ev.score,0)/100.0) filter(where ev.decision='approved'),0),now()
from public.employees e left join public.tasks t on t.assigned_to=e.id and t.period_id=p_period left join lateral(select c1.* from public.task_claims c1 where c1.task_id=t.id order by c1.version desc limit 1)c on true left join public.task_evaluations ev on ev.claim_id=c.id where e.active group by e.id
on conflict(period_id,employee_id) do update set total_assigned=excluded.total_assigned,total_submitted=excluded.total_submitted,total_approved=excluded.total_approved,overdue_count=excluded.overdue_count,completion_rate=excluded.completion_rate,on_time_rate=excluded.on_time_rate,avg_score=excluded.avg_score,weighted_points=excluded.weighted_points,refreshed_at=now();
with r as(select period_id,employee_id,dense_rank() over(partition by period_id order by weighted_points desc,avg_score desc,on_time_rate desc) rnk from public.leaderboard_weekly where period_id=p_period) update public.leaderboard_weekly l set rank=r.rnk from r where l.period_id=r.period_id and l.employee_id=r.employee_id;end $$;
